[package]
name = "unlocker-helper"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "unlocker-helper"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
plist = "1.7"
unlocker-core = { workspace = true }
